// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHGHKMNK_1TZqGvU0NJnhsABvBBl8Bb8',
    appId: '1:911122000942:web:964e871855ef440e86c3bf',
    messagingSenderId: '911122000942',
    projectId: 'ol-exam-paper-hub',
    authDomain: 'ol-exam-paper-hub.firebaseapp.com',
    storageBucket: 'ol-exam-paper-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ezHUNZOe7891nKGNpuoc-gCDdsW99oc',
    appId: '1:911122000942:android:efb602542d52055e86c3bf',
    messagingSenderId: '911122000942',
    projectId: 'ol-exam-paper-hub',
    storageBucket: 'ol-exam-paper-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXUnkso7pVPRtpdXAazdO8if60ttBSDrw',
    appId: '1:911122000942:ios:24d4bfaa6246da7b86c3bf',
    messagingSenderId: '911122000942',
    projectId: 'ol-exam-paper-hub',
    storageBucket: 'ol-exam-paper-hub.appspot.com',
    iosClientId: '911122000942-709b7i8dnqj01m6m58kdupr8hkuat49h.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.olexampaperhub',
  );
}
